# Generated by Django 4.2.2 on 2023-06-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='social_group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('g_type', models.CharField(max_length=255)),
                ('g_media', models.CharField(max_length=255)),
                ('g_name', models.CharField(max_length=255)),
                ('g_purpose', models.CharField(max_length=255)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='social_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=255)),
                ('social_group_id', models.IntegerField()),
                ('created_on', models.DateField()),
                ('social_groups', models.ManyToManyField(to='socialspace.social_group')),
            ],
        ),
    ]
