# Generated by Django 4.2.2 on 2023-06-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_group',
            old_name='g_media',
            new_name='group_description',
        ),
        migrations.RenameField(
            model_name='social_group',
            old_name='g_name',
            new_name='group_name',
        ),
        migrations.RenameField(
            model_name='social_group',
            old_name='g_purpose',
            new_name='group_type',
        ),
        migrations.RemoveField(
            model_name='social_group',
            name='g_type',
        ),
        migrations.AddField(
            model_name='social_group',
            name='social_media',
            field=models.CharField(choices=[('WA', 'Whatsapp'), ('FB', 'Facebook'), ('TW', 'Twitter'), ('LN', 'Linked-in')], default='WA', max_length=2),
        ),
        migrations.AlterField(
            model_name='social_group',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
