# Generated by Django 4.2.2 on 2023-06-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0002_rename_g_media_social_group_group_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_contact',
            name='social_group_id',
        ),
    ]
