# Generated by Django 4.2.2 on 2023-06-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialspace', '0003_remove_social_contact_social_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_contact',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='social_group',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
