# Generated by Django 4.2.2 on 2023-06-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('social_group_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_type', models.CharField(max_length=255)),
                ('g_media', models.CharField(max_length=255)),
                ('g_name', models.CharField(max_length=255)),
                ('g_purpose', models.CharField(max_length=255)),
            ],
        ),
    ]
