# Generated by Django 4.2.2 on 2023-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trevitaessentials', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='img')),
            ],
        ),
    ]
