# Generated by Django 4.2.2 on 2023-07-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trevitaessentials', '0005_upload4'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload4',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
