# Generated by Django 4.2.2 on 2023-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trevitaessentials', '0006_upload4_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pic', models.ImageField(upload_to='upload4')),
            ],
        ),
    ]
