# Generated by Django 4.2.2 on 2023-07-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trevitaessentials', '0007_upload5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pic', models.ImageField(upload_to='upload6')),
            ],
        ),
        migrations.AlterField(
            model_name='upload5',
            name='pic',
            field=models.ImageField(upload_to='upload5'),
        ),
    ]
